
.PHONY: dependencies
dependencies:
	pip install -U setuptools

.PHONY: src
src:
	echo "OK"

.PHONY: build
build:
	echo "OK"

.PHONY: install
install:
	pip install chainer

.PHONY: load_test
load_test:
	python test/load.py
